plugins { id 'com.android.application' }
android {
    namespace 'Rajmal.mmfcr'
    compileSdk 35
    defaultConfig { applicationId "Rajmal.mmfcr"; minSdk 21; targetSdk 35; versionCode 1; versionName "1.0" }
    buildTypes {
        debug { minifyEnabled false; shrinkResources false }
        release { minifyEnabled true; shrinkResources true;  proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro' }
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_1_8; targetCompatibility JavaVersion.VERSION_1_8 }
    aaptOptions {
        noCompress 'html', 'js', 'css', 'png', 'jpg', 'jpeg', 'gif', 'svg', 'webp'
    }
}
dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.startapp:inapp-sdk:5.2.0'
}
